Don't test Python 3.2 on Travis CI.
Because this project didn't support Python 3.2.

File "/home/travis/build/M157q/gettitle/tests/test_gettitle.py", line
3, in <module>

from unittest.mock import Mock
ImportError: No module named mock